# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtmvnormcpp <- function(mean, sigma, blc, lower, upper, init, burn = 10L) {
    .Call(`_tmvtnsim_rtmvnormcpp`, mean, sigma, blc, lower, upper, init, burn)
}

rtmvtcpp <- function(mean, sigma, nu, blc, lower, upper, init, burn = 10L) {
    .Call(`_tmvtnsim_rtmvtcpp`, mean, sigma, nu, blc, lower, upper, init, burn)
}

norm_rej <- function(a, b) {
    .Call(`_tmvtnsim_norm_rej`, a, b)
}

unif_rej <- function(a, b) {
    .Call(`_tmvtnsim_unif_rej`, a, b)
}

halfnorm_rej <- function(a, b) {
    .Call(`_tmvtnsim_halfnorm_rej`, a, b)
}

exp_rej <- function(a, b) {
    .Call(`_tmvtnsim_exp_rej`, a, b)
}

rtnormcpp <- function(mean, sd, lower, upper) {
    .Call(`_tmvtnsim_rtnormcpp`, mean, sd, lower, upper)
}

